sudo: true
language: haskell

git:
  depth: 5

cabal: "2.4"

cache:
  directories:
  - "$HOME/.cabal/store"

matrix:
  include:
  - ghc: 7.10.3
  - ghc: 8.0.2
  - ghc: 8.2.2
  - ghc: 8.4.4
  - ghc: 8.6.3

install:
  - ghc --version
  - cabal --version
  - cabal new-update
  - cabal new-build -fWerror --enable-tests --enable-library-coverage --enable-benchmarks

script:
  - cabal new-test
  - wget https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh -O - --quiet | sh -s .
  - cabal check

after_script:
  - cabal new-install hpc-coveralls
  - ~/.cabal/bin/hpc-coveralls --display-report quickcheck-spec
