sudo: true
language: haskell

git:
  depth: 5

cabal: "3.0"

cache:
  directories:
  - "$HOME/.cabal/store"

matrix:
  include:
  - ghc: 7.8.4
  - ghc: 7.10.3
  - ghc: 8.0.2
  - ghc: 8.2.2
  - ghc: 8.4.4
  - ghc: 8.6.5
  - ghc: 8.8.1

install:
  - ghc --version
  - cabal --version
  - cabal update
  - cabal build -fWerror --enable-tests

script:
  - cabal test
  - wget https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh -O - --quiet | sh -s .
  - cabal check
